In [3]:
import torch
import numpy as np

In [4]:
a = [1,2,3]
b = np.array([1,2,3], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
t_ones = torch.ones(2,3)
t_ones.shape

torch.Size([2, 3])

In [6]:
#manipulate tensors
t = torch.rand(2,3)
t_tr = t.transpose(0,1)
print(t.shape, '->', t_tr.shape)

t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t_reshape.shape)



torch.Size([2, 3]) -> torch.Size([3, 2])
torch.Size([5, 6])


In [10]:
t = torch.zeros(1, 2, 1, 4, 1)
t_squeeze = t.squeeze(2)
print(t.shape, '->', t_squeeze.shape)

torch.Size([1, 2, 1, 4, 1]) -> torch.Size([1, 2, 4, 1])


In [12]:
# element-wise operations
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [15]:
#matrix multiplication
t5 = torch.matmul(t1, t2.transpose(0,1))
t5

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])

In [19]:
# calculate L^p norm of linear algebra operations

from torch._dynamo.utils import T7


t6 = torch.linalg.norm(t1, ord=2, dim=1)
print(t6)

t7 = np.sqrt(np.sum(np.square(t1.numpy()), axis=1))
print(t7)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])
[0.67846215 0.5078282  1.1162277  0.5487652  0.18525197]


In [24]:
# concatennation

A = torch.ones(3)
B = torch.zeros(2)

print(A.shape)
print(B.shape)
C = torch.concat((A, B), axis=0)
print(C)

torch.Size([3])
torch.Size([2])
tensor([1., 1., 1., 0., 0.])


In [26]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t, batch_size=3, drop_last=False)

for idx, item in enumerate(data_loader):
    print(item)

tensor([0., 1., 2.])
tensor([3., 4., 5.])


In [27]:
# joint dataset
from torch.utils.data import Dataset

X = torch.randn(100, 2)
y = np.arange(100)

class JointDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [29]:
joint_dataset = JointDataset(X, y)

for item in joint_dataset:
    print("X: ", item[0], " y: ", item[1])

X:  tensor([ 1.8793, -0.0721])  y:  0
X:  tensor([ 0.1578, -0.7735])  y:  1
X:  tensor([0.1991, 0.0457])  y:  2
X:  tensor([ 0.1530, -0.4757])  y:  3
X:  tensor([-0.1110,  0.2927])  y:  4
X:  tensor([-0.1578, -0.0288])  y:  5
X:  tensor([ 2.3571, -1.0373])  y:  6
X:  tensor([ 1.5748, -0.6298])  y:  7
X:  tensor([-0.9274,  0.5451])  y:  8
X:  tensor([ 0.0663, -0.4370])  y:  9
X:  tensor([0.7626, 0.4415])  y:  10
X:  tensor([1.1651, 2.0154])  y:  11
X:  tensor([0.1374, 0.9386])  y:  12
X:  tensor([-0.1860, -0.6446])  y:  13
X:  tensor([ 1.5392, -0.8696])  y:  14
X:  tensor([-3.3312, -0.7479])  y:  15
X:  tensor([-0.0255, -1.0233])  y:  16
X:  tensor([-0.5962, -1.0055])  y:  17
X:  tensor([-0.2106, -0.0075])  y:  18
X:  tensor([1.6734, 0.0103])  y:  19
X:  tensor([-0.7040, -0.1853])  y:  20
X:  tensor([-0.9962, -0.8313])  y:  21
X:  tensor([-0.4610, -0.5601])  y:  22
X:  tensor([ 0.3956, -0.9823])  y:  23
X:  tensor([-0.5065,  0.0998])  y:  24
X:  tensor([-0.6540,  0.7317])  y:  25
X:  te

In [31]:
data_loader = DataLoader(joint_dataset, batch_size=3, shuffle=True)

In [32]:
for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', 'x:', batch[0],
'\n y:', batch[1])

batch 1: x: tensor([[ 0.4730, -0.4286],
        [ 1.7997,  0.2824],
        [ 0.3956, -0.9823]]) 
 y: tensor([58, 95, 23])
batch 2: x: tensor([[-1.4782, -1.1334],
        [ 0.5149, -1.8475],
        [ 0.1032,  1.1004]]) 
 y: tensor([39, 82, 78])
batch 3: x: tensor([[-0.7040, -0.1853],
        [ 0.9055,  1.0463],
        [ 0.1991,  0.0457]]) 
 y: tensor([20, 88,  2])
batch 4: x: tensor([[1.3352, 0.6043],
        [1.6734, 0.0103],
        [1.8364, 1.3245]]) 
 y: tensor([36, 19, 91])
batch 5: x: tensor([[ 0.6614,  1.1899],
        [-0.3030, -1.7618],
        [-0.6240, -0.9773]]) 
 y: tensor([32, 50, 66])
batch 6: x: tensor([[ 0.3096,  1.5207],
        [-0.8825,  0.5318],
        [-0.7064,  2.5571]]) 
 y: tensor([68, 85, 63])
batch 7: x: tensor([[ 2.2952,  0.6749],
        [ 0.2546, -0.5020],
        [ 0.2352,  1.9142]]) 
 y: tensor([54, 28, 90])
batch 8: x: tensor([[ 1.5392, -0.8696],
        [-0.5065,  0.0998],
        [ 0.5514, -1.5474]]) 
 y: tensor([14, 24, 59])
batch 9: x: tensor([[-

In [33]:
for epoch in range(2):
    print(f'epoch {epoch+1}')
    for i, batch in enumerate(data_loader, 1):
        print(f'batch {i}:', 'x:', batch[0],
'\n y:', batch[1])

epoch 1
batch 1: x: tensor([[ 0.1991,  0.0457],
        [-0.7040, -0.1853],
        [ 1.7837, -0.1954]]) 
 y: tensor([ 2, 20, 81])
batch 2: x: tensor([[ 0.3539,  1.1996],
        [-0.9274,  0.5451],
        [-0.1578, -0.0288]]) 
 y: tensor([49,  8,  5])
batch 3: x: tensor([[-0.7064,  2.5571],
        [ 0.5707, -0.1348],
        [ 0.8748,  0.9873]]) 
 y: tensor([63, 98, 67])
batch 4: x: tensor([[ 0.8165, -0.9135],
        [ 1.2858,  0.8168],
        [ 2.2952,  0.6749]]) 
 y: tensor([33, 41, 54])
batch 5: x: tensor([[-0.0052, -0.0789],
        [ 0.2352,  1.9142],
        [ 0.5431,  0.6607]]) 
 y: tensor([71, 90, 53])
batch 6: x: tensor([[-0.5206,  1.3548],
        [ 0.1530, -0.4757],
        [-0.1860, -0.6446]]) 
 y: tensor([89,  3, 13])
batch 7: x: tensor([[-0.1034, -0.1512],
        [-1.0412,  0.7323],
        [ 0.4175, -0.2127]]) 
 y: tensor([37, 29, 64])
batch 8: x: tensor([[ 0.2911,  1.9907],
        [-0.9276,  1.1120],
        [-0.8825,  0.5318]]) 
 y: tensor([31, 35, 85])
batch 9: