In [ ]:
import torch

# build computation graph
def compute_z(a, b, c):
    r1 = torch.sub(a, b)
    r2 = torch.mul(r1, 2)
    r3 = torch.add(r2, c)
    return r3

In [4]:
print('Scalar Inputs:', compute_z(torch.tensor(1),
    torch.tensor(2), torch.tensor(3)))
print('Rank 1 Inputs:', compute_z(torch.tensor([1]),
    torch.tensor([2]), torch.tensor([3])))
print('Rank 2 Inputs:', compute_z(torch.tensor([[1]]),
    torch.tensor([[2]]), torch.tensor([[3]])))

Scalar Inputs: tensor(1)
Rank 1 Inputs: tensor([1])
Rank 2 Inputs: tensor([[1]])


In [5]:
a = torch.tensor(3.14, requires_grad=True)
b = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(a)
print(b)

tensor(3.1400, requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [6]:
import torch.nn as nn

torch.manual_seed(1)
w=torch.empty(2,3)
print(w)
nn.init.xavier_normal_(w)
print(w)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.4183,  0.1688,  0.0390],
        [ 0.3930, -0.2858, -0.1051]])


In [7]:
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.w1=torch,empty(2,3, requires_grad=True)
        self.w2=torch.empty(3,2, requires_grad=True)

        nn.init.xavier_normal_(self.w1)
        nn.init.xavier_normal_(self.w2)

In [11]:
#compute gradient
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.5, requires_grad=True)
x = torch.tensor([1.4])
y = torch.tensor([2.1])
z = torch.add(torch.mul(w, x), b)
loss = (y-z).pow(2).sum()
print(loss)

loss.backward()
print("dl/dw: ", w.grad)
print("dl/db: ", b.grad)



tensor(0.0400, grad_fn=<SumBackward0>)
dl/dw:  tensor(-0.5600)
dl/db:  tensor(-0.4000)
